src/main/java/domain/Address.java
package domain;

public class Address {

	private String street = "";
	private String number = "";
	private String postcode = "";
	private String city = "";
	
	public Address() {}

	public String getStreet() { return street; }
	public void setStreet(String street) { this.street = street; }

	public String getNumber() { return number; }
	public void setNumber(String number) { this.number = number; }

	public String getPostcode() { return postcode; }
	public void setPostcode(String postcode) { this.postcode = postcode; }

	public String getCity() { return city; }
	public void setCity(String city) { this.city = city; }
	
	
}

src/main/java/domain/Break.java
package domain;

public class Break implements Comparable<Break> {

	private int id;
	private Player player;	
	private Match match;
	private int value;
	
	public Break() {
		this.value = 0;
	}

	public int getId() { return id; }
	public void setId(int id) { this.id = id; }

	public Player getPlayer() { return player; }
	public void setPlayer(Player player) { this.player = player; }
	
	public int getValue() { return value; }
	public void setValue(int value) { this.value = value; }

	public Match getMatch() { return match; }
	public void setMatch(Match match) { this.match = match; }
		
	public int compareTo(Break other) {		
		return this.getValue() - other.getValue();
	}
	
	@Override
	public String toString() {
		return String.valueOf(value);
	}
	
	@Override
	public boolean equals(Object other) {
		if (other != null && other instanceof Break) {
			Break that = (Break)other;
			return this.value == that.getValue();
		} else {
			return false;
		}
	}
}

src/main/java/domain/EventType.java
package domain;

import org.apache.commons.lang.StringUtils;


public enum EventType {
	// position determines position in ranking-table
	
	SINGLEMATCH("SM"),
	SUBTOURNAMENT_NOHANDICAP("TZH"),
	SUBTOURNAMENT_HANDICAP("TMH");
	
	private EventType(String displayValue) {
		this.displayValue = displayValue;
	}
	
	public String getDisplayValue() {
		return this.displayValue;
	}
	
	private String displayValue = StringUtils.EMPTY;
}

src/main/java/domain/InterclubDivision.java
package domain;

import java.util.HashSet;
import java.util.Set;

public class InterclubDivision {

	private int id;
	private String name;
	private int sortorder;
	private Set<InterclubTeam> teams = new HashSet<InterclubTeam>();
	
	public InterclubDivision() {}
	
	public InterclubDivision(int id, String name, int sortorder) {
		this.id = id;
		this.name = name;
		this.sortorder = sortorder;
	}

	public int getId() { return id; }
	public void setId(int id) { this.id = id; }

	public String getName() { return name; }
	public void setName(String name) { this.name = name; }

	public Set<InterclubTeam> getTeams() { return teams; }
	public void setTeams(Set<InterclubTeam> teams) { this.teams = teams; }

	public int getSortorder() { return sortorder; }
	public void setSortorder(int sortorder) { this.sortorder = sortorder; }
}

src/main/java/domain/InterclubTeam.java
package domain;

import java.util.ArrayList;
import java.util.List;

public class InterclubTeam {

	private int id;
	private String name;
	private InterclubDivision interclubDivision;
	private List<Player> players = new ArrayList<Player>();

	public InterclubTeam() {}

	public void setPlayer1(Player player) {		
		player.setInterclubTeam(this);
		player.setInterclubRank(0);
		players.add(0, player);		
	}
	
	public Player getPlayer1() {
		return players.get(0);
	}
	
	public void setPlayer2(Player player) {
		players.add(1, player);
		player.setInterclubTeam(this);
		player.setInterclubRank(1);
	}
	
	public Player getPlayer2() {
		return players.get(1);
	}
	
	public void setPlayer3(Player player) {
		if (player != null) {
			players.add(2, player);
			player.setInterclubTeam(this);
			player.setInterclubRank(2);
		}
	}
	
	public Player getPlayer3() {
		return players.get(2);
	}
	
	public boolean contains(Player p) {
		return players.contains(p);
	}	
	
	
	public Player getPlayer(int index) throws Exception {
		if (index < 3) {
			return players.get(index);
		} else {
			throw new Exception("index should be between 0 and 3");
		}
	}
	
	
	
	public int getId() { return id; }
	public void setId(int id) { this.id = id; }

	public String getName() { return name; }
	public void setName(String name) { this.name = name; }

	public List<Player> getPlayers() { return players; }
	public void setPlayers(List<Player> players) { this.players = players; }

	public InterclubDivision getInterclubDivision() { return interclubDivision; }
	public void setInterclubDivision(InterclubDivision interclubDivision) { this.interclubDivision = interclubDivision; }
	
}

src/main/java/domain/KnockoutMatch.java
package domain;


public class KnockoutMatch extends Match implements Comparable<KnockoutMatch> {
	
	public enum Type {
		FINAL(2) {
			public int getPointsWinner(SubTournament event) {
				return event.getPointsWinnerF();
			}
			public int getPointsLoser(SubTournament event) {
				return event.getPointsLoserF();				
			}
		},
		SEMI_FINAL(4) {
			public int getPointsWinner(SubTournament event) {
				return event.getPointsLoserF();
			}
			public int getPointsLoser(SubTournament event) {
				return event.getPointsLoser2F();
			}
		},
		QUARTER_FINAL(8) {
			public int getPointsWinner(SubTournament event) {
				return event.getPointsLoser2F();
			}
			public int getPointsLoser(SubTournament event) {
				return event.getPointsLoser4F();				
			}
		},
		EIGHT_FINAL(16) {
			public int getPointsWinner(SubTournament event) {
				return event.getPointsLoser4F();
			}
			public int getPointsLoser(SubTournament event) {
				return event.getPointsLoser8F();
			}
		},
		SIXTEENTH_FINAL(32) {
			public int getPointsWinner(SubTournament event) {
				return event.getPointsLoser8F();
			}
			public int getPointsLoser(SubTournament event) {
				return event.getPointsLoser16F();				
			}
		};
		
		private Type(int value) {
			this.value = value;
		}
		
		private int value;

		public int getValue() { return value; }
		public void setValue(int value) { this.value = value; }
		
		public abstract int getPointsWinner(SubTournament event);
		public abstract int getPointsLoser(SubTournament event);
		
	}
	
	private int position;
	private KnockoutRound knockoutRound;
	
	public KnockoutMatch() {}

	public int getPosition() { return position; }
	public void setPosition(int position) { this.position = position; }

	public KnockoutRound getKnockoutRound() { return knockoutRound; }
	public void setKnockoutRound(KnockoutRound knockoutRound) { this.knockoutRound = knockoutRound; }
	
	public int getPointsLoser(SubTournament event) {
		Player loser = getLoser();
		int scoreLoser = getScore(loser);
		if (scoreLoser == -1) {
			if (this.isFirstMatchForPlayer(loser)) {
				return -1;
			} else {
				return -getType().getPointsLoser(event);
			}
		} else {
			return getType().getPointsLoser(event) + (scoreLoser * event.getPointsFrameKnockout());
		}
	}
	
	public int getPointsWinner(SubTournament event) {
		return getType().getPointsWinner(event);
	}
	
	public boolean isFirstMatchForPlayer(Player player) {
		KnockoutMatch match = knockoutRound.getFirstMatchForPlayer(player);
		return this == match;
	}
	
	public Type getType() {
		for (Type t : Type.values()) {
			if (getPosition() < t.getValue()) {
				return t;
			}
		}
		
		return null;
	}

	
	public int compareTo(KnockoutMatch o) {		
		return o.getPosition() - this.getPosition();
	}
	
	@Override
	public boolean equals(Object other) {
		if (other instanceof KnockoutMatch) {
			KnockoutMatch that = (KnockoutMatch)other;
			return super.equals(that) && this.getPosition() == that.getPosition();
		} else {
			return false;
		}
	}
}

src/main/java/domain/KnockoutRound.java
package domain;

import java.util.HashSet;
import java.util.Set;
import java.util.TreeSet;

import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.collections.Predicate;

public class KnockoutRound {
	
	private int id;
	private String name;
	private SubTournament subTournament;
	private Set<KnockoutMatch> matches = new TreeSet<KnockoutMatch>();
		
	private Set<Player> players = new TreeSet<Player>();
	
	public KnockoutRound() {}
	
	public int getId() { return id; }
	public void setId(int id) { this.id = id; }

	public SubTournament getSubTournament() { return subTournament; }
	public void setSubTournament(SubTournament subTournament) { this.subTournament = subTournament; }

	public Set<KnockoutMatch> getMatches() { return matches; }
	public void setMatches(Set<KnockoutMatch> matches) { this.matches = matches; }

	public String getName() { return name; }
	public void setName(String name) { this.name = name; }
	
	/**
	 * returns the first match the player has played in this knockoutround
	 */
	public KnockoutMatch getFirstMatchForPlayer(final Player player) {
		return (KnockoutMatch)CollectionUtils.find(matches, new Predicate() {
			public boolean evaluate(Object match) {
				return (((KnockoutMatch)match).getPlayerA().equals(player) ||
						((KnockoutMatch)match).getPlayerB().equals(player));
			}
		});
	}
	
	public void addMatch(KnockoutMatch match) {
		if (getMatches().contains(match)) {
			getMatches().remove(match);
		}
		
		if (match.getKnockoutRound() == null) {
			match.setKnockoutRound(this);
		}
		getMatches().add(match);
		
	}
	
	public Set<Player> getPlayers() { 
		if (players.isEmpty()) {
			if ( getSubTournament().getPoules().isEmpty()) {				
				Set<TournamentPlayer> subscribers = getSubTournament().getTournament().getSubscribers();
				Set<Player> players = new HashSet<Player>();
				for (TournamentPlayer tp : subscribers) {
					players.add(tp.getPlayer());					
				}
				return players;
			} else {
				for (Poule p : getSubTournament().getPoules()) {
					players.addAll(p.getWinners());
				}
			}
		}
		return players;
	}
		
	public void setPlayers(Set<Player> players) { this.players = players; }
	
	/**
	 * Get the height of the knockout-table.  
	 * Height = upperbound( log2(number_of_players) ) - 1
	 */	
	public int getHeight() {
		return (int)Math.ceil((Math.log(getPlayers().size()) / Math.log(2))) - 1;
	}	
	
	/**
	 * For each player in knockout-round, calculate his points
	 * Matches are sorted and traversed from lowest-rank to highest-rank (= FINAL)
	 */	
//	public Hashtable<Player, Tuple<Integer, Integer>> calculatePoints() {
//		
//		Hashtable<Player, Tuple<Integer, Integer>> points = new Hashtable<Player, Tuple<Integer, Integer>>();
//		
//		for (KnockoutMatch match : getMatches()) {
//			
//			Player pA = match.getPlayerA();
//			int scoreA = (match.getScoreA() == -1) ? 0 : match.getScoreA();
//			int highestBreakA = match.getHighestBreak(pA).getValue();
//			
//			Player pB = match.getPlayerB();
//			int scoreB = (match.getScoreB() == -1) ? 0 : match.getScoreB();
//			int highestBreakB = match.getHighestBreak(pB).getValue();
//									
//			if (!points.containsKey(pA)) {
//				points.put(pA, new Tuple<Integer, Integer>(0, 0));
//			}
//						
//			if (!points.containsKey(pB)) {
//				points.put(pB, new Tuple<Integer, Integer>(0, 0));
//			}
//			
//			Tuple<Integer, Integer> pointsA = points.get(pA);
//			Tuple<Integer, Integer> pointsB = points.get(pB);
//			
//			switch(match.getType()) {
//			case EIGHT_FINAL:
//				if (scoreA < scoreB) {
//					pointsA.setValue1(subTournament.getPointsLoserEF() + scoreA * 2);
//				} else {
//					//points.put(pB, 15 + scoreB * 2);
//					pointsB.setValue1(subTournament.getPointsLoserEF() + scoreB * 2);
//				}				
//				break;
//				
//			case QUARTER_FINAL:
//				if (scoreA < scoreB) {
//					pointsA.setValue1(subTournament.getPointsLoserQF() + scoreA * 2);
//				} else {
//					//points.put(pB, 15 + scoreB * 2);
//					pointsB.setValue1(subTournament.getPointsLoserQF() + scoreB * 2);
//				}
//				
//				break;
//				
//			case SEMI_FINAL:
//				if (scoreA < scoreB) {
//					pointsA.setValue1(subTournament.getPointsLoserSF() + scoreA * 2);
//				} else {
//					//points.put(pB, 15 + scoreB * 2);
//					pointsB.setValue1(subTournament.getPointsLoserSF() + scoreB * 2);
//				}
//				
//				break;
//				
//			case FINAL:
//				if (scoreA < scoreB) {
//					pointsA.setValue1(subTournament.getPointsLoserF() + scoreA * 2);
//					pointsB.setValue1(subTournament.getPointsWinnerF());
//				} else {
//					//points.put(pB, 15 + scoreB * 2);
//					pointsB.setValue1(subTournament.getPointsLoserF() + scoreB * 2);
//					pointsA.setValue1(subTournament.getPointsWinnerF());
//				}
//				
//				break;
//			}
//			
//			if (highestBreakA > pointsA.getValue2()) {
//				pointsA.setValue2(highestBreakA);
//			}
//			if (highestBreakB > pointsB.getValue2()) {
//				pointsB.setValue2(highestBreakB);
//			}
//			
//			points.put(pA, pointsA);
//			points.put(pB, pointsB);
//			
//		}
//		return points;
//	}
}

src/main/java/domain/Match.java
package domain;

import java.util.HashSet;
import java.util.Set;

public abstract class Match {

	protected int id;
	protected Player playerA;
	protected Player playerB;
	protected int scoreA;
	protected int scoreB;	
	protected Set<Break> breaks = new HashSet<Break>();

	protected Match() {}
	
	protected Match(int id, Player playerA, Player playerB) {
		this.id = id;
		this.playerA = playerA;
		this.playerB = playerB;
	}
	
	public int getId() { return id; }
	public void setId(int id) { this.id = id; }
	
	public Player getPlayerA() { return playerA; }
	public void setPlayerA(Player playerA) { this.playerA = playerA; }
	
	public Player getPlayerB() { return playerB; }
	public void setPlayerB(Player playerB) { this.playerB = playerB; }

	public int getScoreA() { return scoreA; }
	public void setScoreA(int scoreA) { this.scoreA = scoreA; }

	public int getScoreB() { return scoreB; }
	public void setScoreB(int scoreB) { this.scoreB = scoreB; }

	public Set<Break> getBreaks() { return breaks; }
	public void setBreaks(Set<Break> breaks) { this.breaks = breaks; }
		
	public Break getHighestBreakPlayerA() { return getHighestBreak(playerA); }
	public Break getHighestBreakPlayerB() { return getHighestBreak(playerB); }
		
	/**
	 * get highest break for a particular player in this match 
	 */
	public Break getHighestBreak(Player player) {
		Break highest = new Break();
		for (Break b : getBreaks()) {
			if (b.getPlayer().equals(player) && (highest == null || highest.getValue() < b.getValue())) {
				highest = b;
			}
		}
		
		return highest;
	}
	
	public Player getWinner() {
		if (scoreA > scoreB) {
			return getPlayerA();
		} else {
			return getPlayerB();
		}
	}
	
	public Player getLoser() {
		if (getPlayerA().equals(getWinner())) {
			return getPlayerB();
		} else {
			return getPlayerA();
		}
	}
	
	public boolean isPlayed() {
		return (scoreA != -1) || (scoreB != -1);
	}
	
	public int getScore(Player player) {
		if (player.equals(getPlayerA())) {
			return scoreA;
		} else {
			return scoreB;
		}
	}
	
	@Override
	public boolean equals(Object other) {
		if (other instanceof Match) {
			Match that = (Match)other;						
			return (this.getPlayerA().equals(that.getPlayerA()) && 
					this.getPlayerB().equals(that.getPlayerB()) &&
					this.getScoreA() == that.getScoreA() &&
					this.getScoreB() == that.getScoreB());
		} else {
			return false;
		}
	}
}

src/main/java/domain/PouleMatch.java
package domain;

public class PouleMatch extends Match {
	
	private Poule poule;
		
	public PouleMatch() {}
	
	public PouleMatch(int id, Player playerA, Player playerB, Poule poule) {
		super(id, playerA, playerB);
		this.poule = poule;
	}

	public Poule getPoule() { return poule; }
	public void setPoule(Poule poule) { this.poule = poule; } 		
}

src/main/java/domain/SingleMatchPeriod.java
package domain;

import java.util.List;
import java.util.Set;
import java.util.TreeSet;

import org.apache.commons.collections.CollectionUtils;
import org.apache.commons.collections.Predicate;

import domain.visitor.AbstractRankingVisitor;

public class SingleMatchPeriod extends TournamentEvent {

	private Set<SingleMatch> matches = new TreeSet<SingleMatch>();
	
	public SingleMatchPeriod() {}

	public Set<SingleMatch> getMatches() { return matches; }
	public void setMatches(Set<SingleMatch> matches) { this.matches = matches; }
	
	@SuppressWarnings(value="all")
	public List<SingleMatch> getMatchesA() { 
		return (List<SingleMatch>) CollectionUtils.select(matches, new Predicate() {
			
			public boolean evaluate(Object object) {
				SingleMatch match = (SingleMatch)object;
				return 
					"A".equalsIgnoreCase(match.getPlayerA().getGrade(tournament)) &&
					"A".equalsIgnoreCase(match.getPlayerB().getGrade(tournament));  
			}
		});					
	}
	
	@SuppressWarnings(value="all")
	public List<SingleMatch> getMatchesB() {
		
		return (List<SingleMatch>) CollectionUtils.select(matches, new Predicate() {
			
			public boolean evaluate(Object object) {
				SingleMatch match = (SingleMatch)object;
				return 
					"B".equalsIgnoreCase(match.getPlayerA().getGrade(tournament)) &&
					"B".equalsIgnoreCase(match.getPlayerB().getGrade(tournament)); 
			}
		});					
	}
	
	public void addMatch(SingleMatch match) {
		if (match.getPeriod() == null) {
			match.setPeriod(this);
		}
		
		getMatches().add(match);
	}
	
	public void accept(AbstractRankingVisitor visitor) {
		visitor.setEvent(this);
		for (SingleMatch match : getMatches()) {
			visitor.visitSingleMatch(match);
		}
	}
	
	/**
	 * retrieve highest break of a particular player in this tournament-event
	 */
	public Break getHighestBreak(Player player) {
		SingleMatch match = findMatch(player);
		return match.getHighestBreak(player);
	}
		
	private SingleMatch findMatch(Player player) {
		for (SingleMatch match : getMatches()) {
			if (match.getPlayerA().equals(player) || match.getPlayerB().equals(player)) {
				return match;
			}
		}
		return null;
	}
}

src/main/webapp/WEB-INF/jsp/calendar.jsp
<div style="background-color: red; border: 1px solid black">
	bliep
</div>

src/main/webapp/WEB-INF/jsp/enterResults_SingleMatch.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"  %>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="dt" uri="/WEB-INF/tags/taglibs-datetime.tld" %>


	<div class="panel">
	
		
		<c:url value="/enterResults.htm" var="submitSingleMatchURL">
			<c:param name="tournamentId" value="${tournament.id}" />
			<c:param name="periodId" value="${period.id}" />
		</c:url>
		
		<form method="POST" action=<c:out value="${submitSingleMatchURL}"/>>
			<b>
			Ingave resultaten voor <c:out value="${period.name}" /><br />
			<dt:format pattern="dd/MM/yyyy"><c:out value="${period.fromDate.time}"/></dt:format> - <dt:format pattern="dd/MM/yyyy"><c:out value="${period.toDate.time}"/></dt:format>
			</b>
			<br /><br />
			<table>
				<tr>
					<td>
						<b>datum</b>
					</td>
					<td>
						<input type="text" name="date" />  
					</td>
				</tr>
				<tr>									
					<td>
						<b>resultaat</b>
					</td>
					<td>
						<select name="playerA">
							<c:forEach items="${tournament.subscribers}" var="subscription">
								<option value="${subscription.player.id}"><c:out value="${subscription.player.name}" /></option>
							</c:forEach>	
						</select>
					</td>
					<td>
						<input type="text" name="scoreA"  size="2" />						
					</td>
					<td>-</td>
					<td>
						<input type="text" name="scoreB"  size="2" />
					</td>
					<td>
						<select name="playerB">
							<c:forEach items="${tournament.subscribers}" var="subscription">
								<option value="${subscription.player.id}"><c:out value="${subscription.player.name}" /></option>
							</c:forEach>	
						</select>
					</td>
				</tr>
				<tr>
					<td>
						<b>breaks</b>
					</td>
					<td colspan="2" align="right">
						<input type="text" name="breaksPlayerA" />
					</td>
					<td />
					<td colspan="2" align="left">
						<input type="text" name="breaksPlayerB" />
					</td>
				</tr>
				<tr>
					<td />
					<td />
					<td />
					<td />
					<td />	
					<td />															
					<td>
						<input type="submit" value="toevoegen" name="addSingleMatch" />
					</td>														
				</tr>			                          
			</table>																										
		 		 
			 <br />
			 <b>
			 Overzicht v/d matches
			 </b>
			 <br /><br />
			 Reeks A<br />
			 <table>
				 <c:forEach items="${period.matchesA}" var="singleMatchA">
					 	<tr>
					 		<td><dt:format pattern="dd/MM/yyyy"><c:out value="${singleMatchA.date.time}"/></dt:format></td>
					 		<td><c:out value="${singleMatchA.playerA}" /></td>
					 		<td><c:out value="${singleMatchA.scoreA}" /></td>
					 		<td>-</td>
					 		<td><c:out value="${singleMatchA.scoreB}" /></td>
					 		<td><c:out value="${singleMatchA.playerB}" /></td>			 		
					 	</tr>
						
				 </c:forEach>
			 </table>
			 <br /><br />
			 Reeks B<br />
			 <table>
				 <c:forEach items="${period.matchesB}" var="singleMatchB">

					 	<tr>
					 		<td><dt:format pattern="dd/MM/yyyy"><c:out value="${singleMatchB.date.time}"/></dt:format></td>
					 		<td><c:out value="${singleMatchB.playerA}" /></td>
					 		<td><c:out value="${singleMatchB.scoreA}" /></td>
					 		<td>-</td>
					 		<td><c:out value="${singleMatchB.scoreB}" /></td>
					 		<td><c:out value="${singleMatchB.playerB}" /></td>			 		
					 	</tr>
						
				 </c:forEach>
			 </table>
			 <br />
			 <hr />
			 <input type="submit" value="Opslaan" name="savePeriod" />
			 <input type="submit" value="Opslaan & beŽindigen" name="finishPeriod" />
			 
		 </form>          					
	</div>

src/main/webapp/WEB-INF/jsp/newNotice.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>

<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"  %>
<%@taglib prefix="security" uri="http://www.springframework.org/security/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>

<script src="js/nicEdit.js"></script>
<script type="text/javascript">bkLib.onDomLoaded(nicEditors.allTextAreas);</script>

<div class="panel">			
	<form:form method="POST" commandName="notice">
		<form:input path="title" />
		<form:textarea path="contents" rows="10" cssStyle="width: 100%"  />
		<input type="submit" value="save" name="saveNotice" />
	</form:form>
	
</div>		
	

src/main/webapp/WEB-INF/jsp/sendMessage.jsp
<div class="panel">

	
	
</div>

src/main/webapp/WEB-INF/jsp/sponsor2.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>

	<!-- Banner Ad code -->
	<div id="bannerAd2" class="sponsorAd">
		<script language="JavaScript" type="text/javascript">
			document.write(myCode_2)		
		</script>
	</div>

src/main/webapp/WEB-INF/jsp/tournamentInfo.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>


<div class="panel">
	reglement<br>
	kalender<br>
	andere opmerkingen<br>
</div>

src/main/webapp/WEB-INF/jsp/viewResults_Round.jsp
<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"  %>
<%@ taglib prefix="security" uri="http://www.springframework.org/security/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="json" uri="/WEB-INF/tags/json.tld" %>

<link href="css/knockoutTable.css" rel="stylesheet" type="text/css" />

<script src="js/json.js"></script>
<script src="js/knockoutTable.js"></script>
<script src="js/prototype.js"></script>

<!-- show poules -->
<div class="panel">
			
	<table width="100%">		
		<tr>
			<c:forEach items="${subTournament.poules}" var="poule">
				<td valign="top" align="center">																
					<div>
						<h1><c:out value="${poule.name}" /></h1>						
						<table cellspacing="0" width="100%" style="border: 1px solid black">
							<tr class="tableheader">								
								<td align="left" style="border-bottom: 1px solid black">speler</th>
								<td align="left" style="border-bottom: 1px solid black">ptn</th>
								<td align="left" style="border-bottom: 1px solid black">brk</th>								
							</tr>
							<c:forEach items="${poule.pouleranking}" var="entry">
								<tr <c:if test="${entry.winner}">class=bold</c:if>>	
									<td align="left"><c:out value="${entry.player}" /></td>
									<td align="left"><c:out value="${entry.framesWon}" /></td>
									<td align="left">
										<c:if test="${entry.brk.value != 0}">
											<c:out value="${entry.brk}" />
										</c:if>						
									</td>
								</tr>								
							</c:forEach>
						</table>
					</div>
				</td>		
			</c:forEach>
		</tr>
	</table>		
</div>

<hr />
	
<!-- show knockout-round -->
<div class="panel">
	<c:if test="${subTournament.knockoutRound != null}">
	
				
		<!-- knockout-table is generated in here using JavaScript -->
		<div id="knockoutTable" style="width: 100%; overflow: visible">							
	
		</div>
			
		<script>								
			generate(<c:out value="${subTournament.knockoutRound.height}"/>, 
     					'1',
					  <json:object>							 
						<json:array name="knockoutMatches" var="knockoutMatch" items="${subTournament.knockoutRound.matches}"> 						
							<json:object>
								<json:property name="position" value="${knockoutMatch.position}"/>
								<json:object name="knockoutMatch">
									<json:property name="playerA" value="${knockoutMatch.playerA.name}"/>
									<json:property name="playerB" value="${knockoutMatch.playerB.name}"/>
									<json:property name="scoreA" value="${knockoutMatch.scoreA}"/>
									<json:property name="scoreB" value="${knockoutMatch.scoreB}"/>
								</json:object>
							</json:object>
						</json:array>				
					  </json:object>, 
					  $("knockoutTable"));
		</script>
	
	</c:if>
</div>				